/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DailySummaryService } from "../dailySummary.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DailySummaryCreateInput } from "./DailySummaryCreateInput";
import { DailySummary } from "./DailySummary";
import { DailySummaryFindManyArgs } from "./DailySummaryFindManyArgs";
import { DailySummaryWhereUniqueInput } from "./DailySummaryWhereUniqueInput";
import { DailySummaryUpdateInput } from "./DailySummaryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DailySummaryControllerBase {
  constructor(
    protected readonly service: DailySummaryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DailySummary })
  @nestAccessControl.UseRoles({
    resource: "DailySummary",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDailySummary(
    @common.Body() data: DailySummaryCreateInput
  ): Promise<DailySummary> {
    return await this.service.createDailySummary({
      data: data,
      select: {
        createdAt: true,
        date: true,
        id: true,
        totalBills: true,
        totalPayments: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DailySummary] })
  @ApiNestedQuery(DailySummaryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DailySummary",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dailySummaries(
    @common.Req() request: Request
  ): Promise<DailySummary[]> {
    const args = plainToClass(DailySummaryFindManyArgs, request.query);
    return this.service.dailySummaries({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,
        totalBills: true,
        totalPayments: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DailySummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DailySummary",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dailySummary(
    @common.Param() params: DailySummaryWhereUniqueInput
  ): Promise<DailySummary | null> {
    const result = await this.service.dailySummary({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,
        totalBills: true,
        totalPayments: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DailySummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DailySummary",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDailySummary(
    @common.Param() params: DailySummaryWhereUniqueInput,
    @common.Body() data: DailySummaryUpdateInput
  ): Promise<DailySummary | null> {
    try {
      return await this.service.updateDailySummary({
        where: params,
        data: data,
        select: {
          createdAt: true,
          date: true,
          id: true,
          totalBills: true,
          totalPayments: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DailySummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DailySummary",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDailySummary(
    @common.Param() params: DailySummaryWhereUniqueInput
  ): Promise<DailySummary | null> {
    try {
      return await this.service.deleteDailySummary({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,
          totalBills: true,
          totalPayments: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
